apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolomy-backend
  labels:
    app: yolomy-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolomy-backend
  template:
    metadata:
      labels:
        app: yolomy-backend
    spec:
      containers:
      - name: yolomy-backend
        image: njongejoseph/njonge-yolo-backend:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"