apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_USERNAME: ZWNobyAtbiBqb3NlcGhuam9uZ2U=  # Base64 encoded "admin"
  MONGO_PASSWORD: ZWNobyAtbiBlTEJxR3dpWFI2Qjdma1gx # Base64 encoded "password"